CREATE DATABASE IF NOT EXISTS mysns
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE mysns;

CREATE TABLE IF NOT EXISTS feed (
	id VARCHAR(32) PRIMARY KEY COMMENT "email",
	contents VARCHAR(4096), 
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
